### ISSUE TITLE
[5.0.0alpha4] build failure with PHP 8.0

### ISSUE THREAD

**Issue by remicollet** [zephir-lang/zephir#2267]
Strangely, build OK with 7.4, KO with 8.0, from the v5.0.0alpha4 tag

```
/builddir/build/BUILD/php80-php-phalcon5-5.0.0~alpha4/NTS/phalcon.zep.c:34672:33: error: 'PsrLinkLinkInterface_ce_ptr' undeclared (first use in this function)
34672 |   Z_PARAM_OBJECT_OF_CLASS(link, PsrLinkLinkInterface_ce_ptr)

```

**Comment by remicollet** [comment]
Could be related to https://github.com/phalcon/cphalcon/commit/afe86a47bafe2bb8885349e526e94b95ae384805

**Comment by remicollet** [comment]
sorry, for noise, bad project
